# Theme
ZSH_THEME="spaceship"

## Spaceship config
SPACESHIP_PROMPT_ASYNC='false'
SPACESHIP_PROMPT_FIRST_PREFIX_SHOW='true'
SPACESHIP_PROMPT_PREFIXES_SHOW='true'
SPACESHIP_PROMPT_SUFFIXES_SHOW='true'
SPACESHIP_RPROMPT_FIRST_PREFIX_SHOW='true'
SPACESHIP_RPROMPT_PREFIXES_SHOW='true'
SPACESHIP_RPROMPT_SUFFIXES_SHOW='true'

#Host
SPACESHIP_HOST_SHOW='always'	
SPACESHIP_HOST_SHOW_FULL='false'	
SPACESHIP_HOST_PREFIX='󱎃 '	
SPACESHIP_HOST_SUFFIX=''
SPACESHIP_HOST_COLOR='blue'	
SPACESHIP_HOST_COLOR_SSH='green'

#Char
SPACESHIP_CHAR_PREFIX=''
SPACESHIP_CHAR_SUFFIX=''
SPACESHIP_CHAR_SYMBOL='陰'
SPACESHIP_CHAR_SYMBOL_SUCCESS='陰'
SPACESHIP_CHAR_SYMBOL_FAILURE='失'
SPACESHIP_CHAR_SYMBOL_ROOT='元'
SPACESHIP_CHAR_SYMBOL_SECONDARY='生'
SPACESHIP_CHAR_COLOR_SUCCESS='green'
SPACESHIP_CHAR_COLOR_FAILURE='red'
SPACESHIP_CHAR_COLOR_SECONDARY='yellow'

#User
SPACESHIP_USER_SHOW='always'
SPACESHIP_USER_PREFIX='  '
SPACESHIP_USER_SUFFIX=' '
SPACESHIP_USER_COLOR='yellow'
SPACESHIP_USER_COLOR_ROOT='red'

#Dir
SPACESHIP_DIR_SHOW='true'
SPACESHIP_DIR_PREFIX=' '
SPACESHIP_DIR_SUFFIX=' '
SPACESHIP_DIR_TRUNC='3'
SPACESHIP_DIR_TRUNC_PREFIX=''
SPACESHIP_DIR_TRUNC_REPO='true'
SPACESHIP_DIR_COLOR='cyan'
SPACESHIP_DIR_LOCK_COLOR='red'

#Nix_shell
SPACESHIP_NIX_SHELL_SHOW='true'
SPACESHIP_NIX_SHELL_ASYNC='false'
SPACESHIP_NIX_SHELL_PREFIX=' '
SPACESHIP_NIX_SHELL_SUFFIX='$SPACESHIP_PROMPT_DEFAULT_SUFFIX'
SPACESHIP_NIX_SHELL_SYMBOL='❄'
SPACESHIP_NIX_SHELL_COLOR='red'

#Git
SPACESHIP_GIT_BRANCH_SHOW='true'
SPACESHIP_GIT_BRANCH_ASYNC='false'
SPACESHIP_GIT_BRANCH_PREFIX=''
SPACESHIP_GIT_BRANCH_SUFFIX=''
SPACESHIP_GIT_BRANCH_COLOR='magenta'
SPACESHIP_GIT_STATUS_SHOW='true'
SPACESHIP_GIT_STATUS_ASYNC='false'
SPACESHIP_GIT_STATUS_PREFIX='['
SPACESHIP_GIT_STATUS_SUFFIX=' ] '
SPACESHIP_GIT_STATUS_COLOR='red'
SPACESHIP_GIT_STATUS_UNTRACKED=' 󱪞'
SPACESHIP_GIT_STATUS_ADDED=' 󱪚'
SPACESHIP_GIT_STATUS_MODIFIED=' 󱪜'
SPACESHIP_GIT_STATUS_RENAMED=' 󰷉'
SPACESHIP_GIT_STATUS_DELETED=' 󱀭'
SPACESHIP_GIT_STATUS_STASHED=' 󱈎'
SPACESHIP_GIT_STATUS_UNMERGED=''
SPACESHIP_GIT_STATUS_AHEAD='⇡'
SPACESHIP_GIT_STATUS_BEHIND='⇣'
SPACESHIP_GIT_STATUS_DIVERGED=''

#Golang
SPACESHIP_GOLANG_SYMBOL=' '

#Exec_time
SPACESHIP_EXEC_TIME_SHOW='true'
SPACESHIP_EXEC_TIME_PREFIX=' '
SPACESHIP_EXEC_TIME_SUFFIX=' '
SPACESHIP_EXEC_TIME_COLOR='yellow'
SPACESHIP_EXEC_TIME_ELAPSED='2'
SPACESHIP_EXEC_TIME_PRECISION='0'

#Exit_code
SPACESHIP_EXIT_CODE_SHOW='true'
SPACESHIP_EXIT_CODE_SYMBOL='󰗼 '
SPACESHIP_EXIT_CODE_PREFIX=''
SPACESHIP_EXIT_CODE_SUFFIX=' '
SPACESHIP_EXIT_CODE_COLOR='red'

#Vi_mode
SPACESHIP_VI_MODE_SHOW='true'
SPACESHIP_VI_MODE_PREFIX=''
SPACESHIP_VI_MODE_INSERT='⫸'
SPACESHIP_VI_MODE_NORMAL='⪢'
SPACESHIP_VI_MODE_VISUAL='⅀'
SPACESHIP_VI_MODE_REPLACE_ONE='⨝'
SPACESHIP_VI_MODE_COLOR='green'
SPACESHIP_VI_MODE_SUFFIX=' '

SPACESHIP_PROMPT_ORDER=(
    host
    user
    dir
    nix_shell
    git_branch
    git_status
    #package
    node
    docker
    #php
    #lua
    python
    golang
    line_sep
    char
    vi_mode
)

SPACESHIP_RPROMPT_ORDER=(
    exec_time
    exit_code
    jobs
)

