#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
polybar &

~/.config/automation/redshell &
xrandr --output DP-1 --mode 1920x1080 --pos 0x0 --rotate right --output DP-2 --off --output DP-3 --off --output HDMI-1 --primary --mode 2560x1080 --pos 1080x163 --rotate normal && \ 
feh --bg-fill $HOME/Interface/desktop.png &

bspc monitor DP-1 -d I II III IV V
bspc monitor HDMI-1 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          18

bspc config split_ratio          0.54
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#EECC44"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a steam desktop='^8' state=floating follow=on

bspc rule -a keepassxc desktop='^1' 
bspc rule -a qbittorrent desktop='^1' 
bspc rule -a Alacritty desktop='^2' 
bspc rule -a steam desktop='^7' 
bspc rule -a Brave-browser desktop='^6' 

sleep 5 &&
alacritty &
keepassxc &
qbittorrent &
sleep 3 && bspc desktop -f ^7 && brave
#steam &
