#! /bin/bash

##zsh config
export ZDOTDIR=$HOME/.config/zsh

## for every file in automation
for script in $HOME/.config/automation/*; do
    echo $script
    $script &
done

#nitrogen --restore
#sleep 1
#picom --experimental-backends -b
#clipit
#polybar main -r
#xautolock -time 30 -locker blurlock

##programs
qbittorrent &
keepassxc &
brave &
notion-app-enhanced &
#lbry &
#steam &
#discord &

sleep 3

##hardware
openrgb -p off &

exit 0
