#! /bin/bash

##zsh config
export ZDOTDIR=$HOME/.config/zsh

## for every file in automation
for script in $HOME/.config/automation/*; do
    echo $script
    $script &
done

##hardware
openrgb -p off &

##programs
qbittorrent &
keepassxc &
brave &
notion-app-enhanced &
lbry &
#steam &
#discord &

sleep 2
exit 0
